---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-12-20260710-125109-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-12
  snapshot: costmanagement-metrics-operator-fbc-v4-12-20260710-125109-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-13-20260710-125110-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-13
  snapshot: costmanagement-metrics-operator-fbc-v4-13-20260710-125110-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-14-20260710-125110-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-14
  snapshot: costmanagement-metrics-operator-fbc-v4-14-20260710-125110-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-15-20260710-125109-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-15
  snapshot: costmanagement-metrics-operator-fbc-v4-15-20260710-125109-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-16-20260710-125109-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-16
  snapshot: costmanagement-metrics-operator-fbc-v4-16-20260710-125109-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-17-20260710-125109-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-17
  snapshot: costmanagement-metrics-operator-fbc-v4-17-20260710-125109-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-18-20260710-125110-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-18
  snapshot: costmanagement-metrics-operator-fbc-v4-18-20260710-125110-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-19-20260710-125110-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-19
  snapshot: costmanagement-metrics-operator-fbc-v4-19-20260710-125110-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-20-20260710-125109-000-2
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-20
  snapshot: costmanagement-metrics-operator-fbc-v4-20-20260710-125109-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-21-20260710-125109-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-21
  snapshot: costmanagement-metrics-operator-fbc-v4-21-20260710-125109-000

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-lbacciot'
    release.appstudio.openshift.io/version: '4.4.2'
    release.appstudio.openshift.io/sha: 'ceb7fcb6b2664eecc936867e35f95bcc2f0d110e'
  name: costmanagement-metrics-operator-fbc-v4-22-20260710-125111-000-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-22
  snapshot: costmanagement-metrics-operator-fbc-v4-22-20260710-125111-000
