---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: "rh-ee-dnakabaa"
  namespace: cost-mgmt-dev-tenant
  name: costmanagement-metrics-operator-4.3.1-prod-1
spec:
  releasePlan: costmanagement-metrics-operator
  snapshot: costmanagement-metrics-operator-20260211-191332-000
  data:
    releaseNotes:
      type: RHSA
      topic: "Cost Management Metrics Operator version 4.3.1 release."
      issues:
        fixed:
          - id: COST-7229
            source: issues.redhat.com
          - id: COST-7232
            source: issues.redhat.com
      cves:
        - key: CVE-2025-11187
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-15467
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-15468
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-15469
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-66199
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-68160
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-69418
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-69419
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-69421
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2025-69420
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2026-22795
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2026-22796
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2026-0861
          component: costmanagement-metrics-operator
          packages:
            - glibc
        - key: CVE-2026-0915
          component: costmanagement-metrics-operator
          packages:
            - glibc
        - key: CVE-2025-15281
          component: costmanagement-metrics-operator
          packages:
            - glibc
      references:
        - https://access.redhat.com/security/updates/classification
        - https://access.redhat.com/security/cve/CVE-2025-11187
        - https://access.redhat.com/security/cve/CVE-2025-15467
        - https://access.redhat.com/security/cve/CVE-2025-15468
        - https://access.redhat.com/security/cve/CVE-2025-15469
        - https://access.redhat.com/security/cve/CVE-2025-66199
        - https://access.redhat.com/security/cve/CVE-2025-68160
        - https://access.redhat.com/security/cve/CVE-2025-69418
        - https://access.redhat.com/security/cve/CVE-2025-69419
        - https://access.redhat.com/security/cve/CVE-2025-69421
        - https://access.redhat.com/security/cve/CVE-2025-69420
        - https://access.redhat.com/security/cve/CVE-2026-22795
        - https://access.redhat.com/security/cve/CVE-2026-22796
        - https://access.redhat.com/security/cve/CVE-2026-0861
        - https://access.redhat.com/security/cve/CVE-2026-0915
        - https://access.redhat.com/security/cve/CVE-2025-15281
        - https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html/getting_started_with_cost_management/steps-to-cost-management
