---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'

  name: costmanagement-metrics-operator-prod-fbc-v4-12-c7r2b-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-12
  snapshot: costmanagement-metrics-operator-fbc-v4-12-c7r2b

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-13-nmdl7-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-13
  snapshot: costmanagement-metrics-operator-fbc-v4-13-nmdl7

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-14-9gv4x-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-14
  snapshot: costmanagement-metrics-operator-fbc-v4-14-9gv4x

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-15-ls7rx-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-15
  snapshot: costmanagement-metrics-operator-fbc-v4-15-ls7rx

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-16-qbzzt-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-16
  snapshot: costmanagement-metrics-operator-fbc-v4-16-qbzzt

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-17-m7znj-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-17
  snapshot: costmanagement-metrics-operator-fbc-v4-17-m7znj

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-18-ld7r4-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-18
  snapshot: costmanagement-metrics-operator-fbc-v4-18-ld7r4

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-19-njmvk-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-19
  snapshot: costmanagement-metrics-operator-fbc-v4-19-njmvk

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: 'rh-ee-dnakabaa'
    release.appstudio.openshift.io/version: '4.1.0'
    release.appstudio.openshift.io/sha: '556df9d0fa1b5d9017130cc96e35d9c524c457b0'
  name: costmanagement-metrics-operator-prod-fbc-v4-20-6wpb6-1
  namespace: cost-mgmt-dev-tenant
spec:
  releasePlan: costmanagement-metrics-operator-fbc-v4-20
  snapshot: costmanagement-metrics-operator-fbc-v4-20-6wpb6
