---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: "rh-ee-lbacciot"
  namespace: cost-mgmt-dev-tenant
  name: costmanagement-metrics-operator-4.4.1-prod-1
spec:
  releasePlan: costmanagement-metrics-operator
  snapshot: costmanagement-metrics-operator-20260609-072014-000
  data:
    releaseNotes:
      type: RHSA
      topic: "Cost Management Metrics Operator version 4.4.1 release."
      issues:
        fixed:
          - id: COST-7474
            source: issues.redhat.com
          - id: COST-7484
            source: issues.redhat.com
          - id: COST-7668
            source: issues.redhat.com
      cves:
        - key: CVE-2026-4878
          component: costmanagement-metrics-operator
          packages:
            - libcap
        - key: CVE-2026-31790
          component: costmanagement-metrics-operator
          packages:
            - openssl
        - key: CVE-2026-2100
          component: costmanagement-metrics-operator
          packages:
            - p11-kit
        - key: CVE-2026-4437
          component: costmanagement-metrics-operator
          packages:
            - glibc
        - key: CVE-2026-4438
          component: costmanagement-metrics-operator
          packages:
            - glibc
        - key: CVE-2026-4046
          component: costmanagement-metrics-operator
          packages:
            - glibc
        - key: CVE-2026-28390
          component: costmanagement-metrics-operator
          packages:
            - openssl
      references:
        - https://access.redhat.com/security/updates/classification
        - https://access.redhat.com/security/cve/CVE-2026-4878
        - https://access.redhat.com/security/cve/CVE-2026-31790
        - https://access.redhat.com/security/cve/CVE-2026-2100
        - https://access.redhat.com/security/cve/CVE-2026-4437
        - https://access.redhat.com/security/cve/CVE-2026-4438
        - https://access.redhat.com/security/cve/CVE-2026-4046
        - https://access.redhat.com/security/cve/CVE-2026-28390
        - https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html/getting_started_with_cost_management/steps-to-cost-management
