apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: deploy-fbc-operator-with-iqe-run-v5-0
  labels:
    upstream-usable: "true"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/project-koku/cost-management-metrics-operator-fbc.git
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/pipelines/deploy-fbc-operator-with-iqe.yaml
  params:
    - name: RELEASED_BUNDLE_IMAGE_OVERRIDE
      value: "registry.redhat.io/costmanagement/costmanagement-metrics-operator-bundle@sha256:fa43be2fd285110e13fb4e782479b28a6e59ffc25da384d4aae745b6d70c74c7"
  timeouts:
    pipeline: "2h30m0s"
  taskRunTemplate:
    serviceAccountName: build-pipeline-costmanagement-metrics-operator-fbc-component-v5-0
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
