apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: deploy-fbc-operator-with-iqe-run-v__VERSION_DASH__
  labels:
    upstream-usable: "true"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/project-koku/cost-management-metrics-operator-fbc.git
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/pipelines/deploy-fbc-operator-with-iqe.yaml
  params:
    - name: RELEASED_BUNDLE_IMAGE_OVERRIDE
      value: ""
  timeouts:
    pipeline: "2h30m0s"
  taskRunTemplate:
    serviceAccountName: build-pipeline-costmanagement-metrics-operator-fbc-component-v__VERSION_DASH__
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
