---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: "rh-ee-dnakabaa"
  namespace: cost-mgmt-dev-tenant
  name: costmanagement-metrics-operator-4.0.0-prod-1
spec:
  releasePlan: costmanagement-metrics-operator
  snapshot: costmanagement-metrics-operator-5lszl
  data:
    releaseNotes:
      type: RHEA
      topic: "Cost Management Metrics Operator version 4.0.0 release."
      issues:
        fixed:
          - id: COST-6058
            source: issues.redhat.com
          - id: COST-6010
            source: issues.redhat.com
