apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/project-koku/cost-management-metrics-operator-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: costmanagement-metrics-operator-fbc-v4-12
    appstudio.openshift.io/component: costmanagement-metrics-operator-fbc-component-v4-12
    pipelines.appstudio.openshift.io/type: build
  name: costmanagement-metrics-operator-fbc-component-v4-12-on-push
  namespace: cost-mgmt-dev-tenant
spec:
  taskRunTemplate:
    serviceAccountName: build-pipeline-costmanagement-metrics-operator-fbc-component-v4-12

  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cost-mgmt-dev-tenant/costmanagement-metrics-operator-fbc-component-v4-12:{{revision}}
  - name: dockerfile
    value: Dockerfile.v4-12
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
      - linux/s390x
      - linux/ppc64le
  pipelineRef:
    name: pipeline-build

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
